version: '3.4'
services:
  gateway:
    volumes:
      - type: bind
        source: ./logs/nginx
        target: /var/log/nginx
    ports:
      - '8080:8080'
    depends_on:
      - users-service
      - batches-service
      - stashes-service

  users-service:
    depends_on:
      - users-mongo
    volumes:
      - type: bind
        source: ./logs/users-service
        target: /app/logs

  batches-service:
    depends_on:
      - batches-mongo
    volumes:
      - type: bind
        source: ./logs/batches-service
        target: /app/logs

  stashes-service:
    depends_on:
      - stashes-mongo
    volumes:
      - type: bind
        source: ./logs/stashes-service
        target: /app/logs

  users-mongo:
    image: mongo:3.6.3-jessie
    command: mongod --port 27017 --smallfiles

  batches-mongo:
    image: mongo:3.6.3-jessie
    command: mongod --port 27018 --smallfiles

  stashes-mongo:
    image: mongo:3.6.3-jessie
    command: mongod --port 27019 --smallfiles
