export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';
export const GET_BATCHES_FROM_USER_DATA = 'GET_BATCHES_FROM_USER_DATA';
export const GET_STASHES_FROM_USER_DATA = 'GET_STASHES_FROM_USER_DATA';