export const GET_SUMMARY_FROM_STASHES = 'GET_SUMMARY_FROM_STASHES';
export const CHANGE_SUMMARY_BOTTLES_AMOUNT = 'CHANGE_SUMMARY_BOTTLES_AMOUNT';
export const CHANGE_SUMMARY_CRATES = 'CHANGE_SUMMARY_CRATES';
export const ADD_STASH = 'CHANGE_BOTTLES_AMOUNT';
export const REMOVE_STASH = 'REMOVE_STASH';
export const CALCULATE_CRATES = 'CALCULATE_CRATES';
export const ADD_STASHES = 'ADD_STASHES';
