version: '3.4'
services:
  users-service:
    build:
      context: ./backend/users-service
      target: builder
    volumes:
      - type: bind
        source: ./backend/users-service/build
        target: /app/build
    ports:
      - '3017:3017'
    command: yarn run start-dev

  users-mongo:
    volumes:
      - users-mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  users-mongodata:
