version: '3.4'
services:
  users-svc:
    build:
      context: ./backend/users-service
      target: builder
    volumes:
      - type: bind
        source: ./backend/users-service/build
        target: /app/build
    ports:
      - '3000:3000'
    command: yarn run start-dev

  users-mongo:
    volumes:
      - users-mongodata:/data/db
    ports:
      - "27017:27017"

  batches-mongo:
    volumes:
      - batches-mongodata:/data/db
    ports:
      - "27018:27018"

  stashes-mongo:
    volumes:
      - stashes-mongodata:/data/db
    ports:
      - "27019:27019"

volumes:
  users-mongodata:
  batches-mongodata:
  stashes-mongodata:
